package koala

/** The site's SVG icons. */
object SvgFile {
    val Aperture = svgPackOf("aperture")
    val Archive = svgPackOf("archive")
    val ArrowLeft = svgPackOf("arrow-left")
    val ArrowRight = svgPackOf("arrow-right")
    val ArrowUp = svgPackOf("arrow-up")
    val ArrowsSort = svgPackOf("arrows-sort")
    val Backspace = svgPackOf("backspace")
    val Book = svgPackOf("book")
    val Boost = svgPackOf("boost")
    val Bulb = svgPackOf("bulb")
    val Calendar = svgPackOf("calendar")
    val CalendarMinus = svgPackOf("calendar-minus")
    val CalendarPlus = svgPackOf("calendar-plus")
    val CaretLeft = svgPackOf("caret-left")
    val CaretUp = svgPackOf("caret-up")
    val Chart = svgPackOf("chart")
    val Check = svgPackOf("check")
    val ChevronDown = svgPackOf("chevron-down")
    val ChevronUp = svgPackOf("chevron-up")
    val City = svgPackOf("city")
    val Clock = svgPackOf("clock")
    val Crosshairs = svgPackOf("crosshairs")
    val CurrentLocation = svgPackOf("current-location")
    val Dashboard = svgPackOf("dashboard")
    val Database = svgPackOf("database")
    val DatabaseArrow = svgPackOf("database-arrow")
    val DatabaseMinus = svgPackOf("database-minus")
    val DatabasePlus = svgPackOf("database-plus")
    val Directions = svgPackOf("directions")
    val Dots = svgPackOf("dots")
    val DotsVertical = svgPackOf("dots-vertical")
    val Earth = svgPackOf("earth")
    val Edit = svgPackOf("edit")
    val ExpandBelow = svgPackOf("expand-below")
    val Eye = svgPackOf("eye")
    val EyeClosed = svgPackOf("eye-closed")
    val EyeMinus = svgPackOf("eye-minus")
    val EyeOff = svgPackOf("eye-off")
    val EyePlus = svgPackOf("eye-plus")
    val Focus = svgPackOf("focus")
    val FrameEye = svgPackOf("frame-eye")
    val Gear = svgPackOf("gear")
    val Github = svgPackOf("github")
    val HeartHandshake = svgPackOf("heart-handshake")
    val Home = svgPackOf("home")
    val Info = svgPackOf("info")
    val Label = svgPackOf("label")
    val LayoutGrid = svgPackOf("layout-grid")
    val LayoutMinimal = svgPackOf("layout-minimal")
    val LayoutRow = svgPackOf("layout-row")
    val Light = svgPackOf("light")
    val Link = svgPackOf("link")
    val Loader = svgPackOf("loader")
    val Magic = svgPackOf("magic")
    val Mail = svgPackOf("mail")
    val MapPin = svgPackOf("map-pin")
    val Menu = svgPackOf("menu")
    val Message = svgPackOf("message")
    val MessageMinus = svgPackOf("message-minus")
    val MessagePlus = svgPackOf("message-plus")
    val Minus = svgPackOf("minus")
    val Moon = svgPackOf("moon")
    val Navigation = svgPackOf("navigation")
    val PanelLeft = svgPackOf("panel-left")
    val PanelRight = svgPackOf("panel-right")
    val Plus = svgPackOf("plus")
    val PlusAbove = svgPackOf("plus-above")
    val Question = svgPackOf("question")
    val Rays = svgPackOf("rays")
    val Ruler = svgPackOf("ruler")
    val RulerMeasure = svgPackOf("ruler-measure")
    val Satellite = svgPackOf("satellite")
    val Search = svgPackOf("search")
    val ShootingStar = svgPackOf("shooting-star")
    val SignOut = svgPackOf("sign-out")
    val Social = svgPackOf("social")
    val Star = svgPackOf("star")
    val StarOff = svgPackOf("star-off")
    val Sun = svgPackOf("sun")
    val Ticket = svgPackOf("ticket")
    val Trash = svgPackOf("trash")
    val User = svgPackOf("user")
    val X = svgPackOf("x")

    // original
    val Bus = svgOf("bus")
    val Flame = svgOf("flame")
    val FlameLarge = svgOf("flame-large")
    val Food = svgOf("food")
    val Guitar = svgOf("guitar")
    val Helm = svgOf("helm")
    val LogoFlame = svgOf("logo-flame")
    val LogoText = svgOf("logo-text")
    val LogoTextLight = svgOf("logo-text-light")
    val LogoTextStreet = svgOf("logo-text-street")
    val Someone = svgOf("someone")
    val SomeoneSmall = svgOf("someone-small")
    val Train = svgOf("train")
    val TransitStop = svgOf("transit-stop")

    // animations
    val CircleLoop = svgOf("circle-loop-beta")
    val LineParticleLoop = svgOf("line-particle-loop")

    // filigree
    val CircularFiligree = svgOf("circular-filigree")
    val CircularFiligreeAnimated = svgOf("circular-filigree-animated")
    val Plant = svgOf("filigree-plant")
}
